# tasks file for kibatic.traefik
---
- name: Create traefik systemd unit
  template:
    src: "{{ traefik_systemd_unit_template }}.j2"
    dest: "{{ traefik_systemd_unit_dest }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart traefik

- name: Ensure install & config directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_install_dir }}"
    - "{{ traefik_config_dir }}"
    - "{{ traefik_log_dir }}"

- name: Create traefik acme.json
  file:
    dest: "{{ traefik_acme_file }}"
    state: touch
    owner: root
    group: root
    mode: 0600

- name: Copy traefik basic auth user file
  template:
    src: "./templates/htpasswd.j2"
    dest: "{{ traefik_dashboard_userfile }}"
    owner: root
    group: root
    mode: 0600

- name: Copy traefik config file
  template:
    src: "{{ traefik_template }}.j2"
    dest: "{{ traefik_config_file }}"
    owner: root
    group: root
    mode: 0744
  notify:
    - Restart traefik

- name: Ensure traefik service is stopped before traefik update
  service:
    name: traefik
    state: stopped
    enabled: yes
  when: traefik_update == "yes"

- name: Download Traefik binary
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
    force: "{{ traefik_update }}"
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "{{ traefik_bin_path }}"

- name: Ensure traefik service is enabled and running
  systemd:
    name: traefik
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install UFW rules for Traefik
  template:
    src: "./templates/traefik.conf.j2"
    dest: "/etc/ufw/applications.d/traefik"
    owner: root
    group: root
    mode: 0644

# UFW management is currently in preview, so better do that manually.
#    sudo ufw allow "Traefik HTTP"